[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npx convex deploy --cmd 'npm run build'"

[template.environment]
  CONVEX_DEPLOY_KEY = "add your Convex deploy key here"
